name: BTTFV-WIP
# Hardcoded mess, but it works, okay?

on:
  push:
    branches: [ dev ]
  pull_request:

env:
  WEBHOOK_URL: https://canary.discord.com/api/webhooks/1104236974761586808/l0eXPqDzX4O9FSaQp_UKgdYdKdPVTCoTFrx8B1utSX79Lr3cGUdER2TG1IHqJBxC24FV
  # For compatibility sake.
  # I'll do this properly later....
  GTAPath: D:/a/bttfv-actions-data/

jobs:
  build:
    runs-on: windows-latest

    steps:
    # This is an awful hack but C'est la vie...
    - name: Clone required libraries and set GTAPath for build. *THIS IS A HACK!*
      run: |
        cd "D:/a/"
        git clone https://github.com/audiorobscrackshack/bttfv-actions-data.git
        echo "GTAPath=D:/a/bttfv-actions-data/" >> $GITHUB_ENV
        cd "D:\a\BackToTheFutureV\BackToTheFutureV"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # try v1.1.3 to resolve warning, if it doesn't work, revert to v1.0.3
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore NuGet packages
      run: nuget restore BackToTheFutureV.sln

    - name: Build solution
      run: msbuild BackToTheFutureV.sln /p:Configuration=Release /verbosity:minimal

    - name: Archive artifact
      run: 7z a BackToTheFutureV.zip D:/a/BackToTheFutureV/BackToTheFutureV/BackToTheFutureV/bin/Release

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BackToTheFutureV - release
        path: "D:/a/BackToTheFutureV/BackToTheFutureV/BackToTheFutureV.zip"
