name: BTTFV-WIP

on:
  push:
    branches: [ dev ]
  pull_request:

env:
  CONFIGURATION: Release
  WEBHOOK_URL: https://www.discord.com/api/webhooks/1104236974761586808/l0eXPqDzX4O9FSaQp_UKgdYdKdPVTCoTFrx8B1utSX79Lr3cGUdER2TG1IHqJBxC24FV
  # For compatibility sake.
  # I'll do this properly later....
  GTAPath: D:/a/bttfv-actions-data/
  # This is the worst hack *ever...*
  APPVEYOR_BUILD_FOLDER: D:/a/BackToTheFutureV/

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # This is an awful hack but C'est la vie...
    - name: Clone required libaries and set GTAPath for build. *THIS IS A HACK!*
      run: |
        cd "D:/a/"
        git clone https://github.com/audiorobscrackshack/bttfv-actions-data.git
        echo "GTAPath=D:/a/bttfv-actions-data/" >> $GITHUB_ENV
        cd "D:\a\BackToTheFutureV\BackToTheFutureV"

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3

    - name: Restore NuGet packages
      run: nuget restore BackToTheFutureV.sln

    - name: Build solution
      run: msbuild BackToTheFutureV.sln /p:Configuration=$env:CONFIGURATION /verbosity:minimal

    - name: Archive artifact
      run: 7z a BackToTheFutureV-release.zip $(Get-ChildItem -Path "$($env:APPVEYOR_BUILD_FOLDER)\BackToTheFutureV\bin\$($env:CONFIGURATION)" -Filter '*.{dll,pdb}' -Recurse -File | Select-Object -ExpandProperty FullName)

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: BackToTheFutureV-release.zip
        path: BackToTheFutureV-release.zip

    - name: Send Webhook Notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        # WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        # FIX: Commenting out in favour of our hack, for now!!
        HOOK_OS_NAME: ${{ runner.os }}
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        cd "D:\a\"
        git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash
